### ISSUE TITLE
Noisy exception in log for every first access for Pages file

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/wasp#64]
```
[WARNING]      [echo] [2023-11-04T01:04:18.746107+01:00] [GF 7.0.11-SNAPSHOT] [SEVERE] [] [org.glassfish.wasp.compiler.Compiler] [tid: _ThreadID=39 _ThreadName=http-listener-1(1)] [levelValue: 1000] [[
[WARNING]      [echo]   Failed to read attributes for file /glassfish7/glassfish/domains/domain1/generated/jsp/testclient/org/apache/jsp/Hello_jsp.class
[WARNING]      [echo] java.nio.file.NoSuchFileException: /glassfish7/glassfish/domains/domain1/generated/jsp/testclient/org/apache/jsp/Hello_jsp.class
[WARNING]      [echo] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[WARNING]      [echo] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[WARNING]      [echo] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[WARNING]      [echo] 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[WARNING]      [echo] 	at org.glassfish.wasp.compiler.Compiler.getLastModifiedTime(Compiler.java:610)
[WARNING]      [echo] 	at org.glassfish.wasp.compiler.Compiler.isOutDated(Compiler.java:472)
[WARNING]      [echo] 	at org.glassfish.wasp.compiler.Compiler.isOutDated(Compiler.java:439)
[WARNING]      [echo] 	at org.glassfish.wasp.JspCompilationContext.compile(JspCompilationContext.java:559)
[WARNING]      [echo] 	at org.glassfish.wasp.servlet.JspServletWrapper.service(JspServletWrapper.java:288)
[WARNING]      [echo] 	at org.glassfish.wasp.servlet.JspServlet.serviceJspFile(JspServlet.java:358)
[WARNING]      [echo] 	at org.glassfish.wasp.servlet.JspServlet.service(JspServlet.java:287)
```

The problem comes from the new `getLastModifiedTime()` method, which logs an exception if the file does not exist yet:

```java
 BasicFileAttributes attributes;
        try {
            attributes = attributeView.readAttributes();
        } catch (IOException e) {
            log.log(SEVERE, "Failed to read attributes for file " + file.getAbsolutePath(), e);
            return 0L;
        }
```

@avpinchuk Shall we check for `java.nio.file.NoSuchFileException` and then not log, or shall we check explicitly for file existing?

**Comment by avpinchuk** [comment]
@arjantijms, review please.
